<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>csvd</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
        <Version>2.0.8</Version>
        <FileVersion>2.0.8</FileVersion>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Spectre.Console" Version="0.55.2" />
        <PackageReference Include="System.CommandLine" Version="2.0.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\csvd.Library\csvd.Library.csproj" />
    </ItemGroup>

</Project>
